-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.activity_type_master
(
    activity_type_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    activity_name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT activity_type_master_pkey PRIMARY KEY (activity_type_id),
    CONSTRAINT activity_type_master_activity_name_key UNIQUE (activity_name)
);

CREATE TABLE IF NOT EXISTS public.alert
(
    "AlertID" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "PatientID" uuid NOT NULL,
    "AlertTypeID" uuid,
    "GeneratedDate" date NOT NULL DEFAULT CURRENT_DATE,
    "ResolvedFlag" boolean DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    "Is_active" boolean DEFAULT true,
    CONSTRAINT alert_pkey PRIMARY KEY ("AlertID")
);

CREATE TABLE IF NOT EXISTS public.appointment
(
    "AppointmentID" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "PatientID" uuid,
    "ClinicID" uuid,
    "ProviderID" uuid,
    "StartDateTime" timestamp with time zone NOT NULL,
    "Status" text COLLATE pg_catalog."default" DEFAULT 'Booked'::text,
    "VisitType" text COLLATE pg_catalog."default" DEFAULT 'Initial'::text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT appointment_pkey PRIMARY KEY ("AppointmentID")
);

CREATE TABLE IF NOT EXISTS public.care_level_master
(
    care_level_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    care_level_name text COLLATE pg_catalog."default" NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT care_level_master_pkey PRIMARY KEY (care_level_id),
    CONSTRAINT care_level_master_care_level_name_key UNIQUE (care_level_name)
);

CREATE TABLE IF NOT EXISTS public.carelevel_master
(
    "LevelName" text COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default",
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT carelevel_master_pkey PRIMARY KEY ("LevelName")
);

CREATE TABLE IF NOT EXISTS public.careplan
(
    "CarePlanID" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "PatientID" uuid NOT NULL,
    "ConditionID" uuid,
    "PlanStatus_ID" uuid,
    "StartDate" date NOT NULL DEFAULT CURRENT_DATE,
    "EndDate" date,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT careplan_pkey PRIMARY KEY ("CarePlanID")
);

CREATE TABLE IF NOT EXISTS public.careplan_activity
(
    "ActivityID" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "CarePlanID" uuid NOT NULL,
    "ActivityType_ID" uuid NOT NULL,
    "Status_ID" uuid,
    "DueDate" date,
    "CompletedDate" date,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT careplan_activity_pkey PRIMARY KEY ("ActivityID")
);

CREATE TABLE IF NOT EXISTS public.clinic_master
(
    clinic_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    site_id uuid NOT NULL,
    clinic_name text COLLATE pg_catalog."default" NOT NULL,
    clinic_address text COLLATE pg_catalog."default",
    specialty_id uuid NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    phone_number text COLLATE pg_catalog."default",
    CONSTRAINT clinic_master_pkey PRIMARY KEY (clinic_id)
);

CREATE TABLE IF NOT EXISTS public.clinical_event
(
    "EventID" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "PatientID" uuid NOT NULL,
    "EventTypeID" uuid NOT NULL,
    "HospitalID" uuid,
    "EventDate" date NOT NULL DEFAULT CURRENT_DATE,
    "OutcomeID" text COLLATE pg_catalog."default",
    "LOS_Days" integer,
    "Notes" text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT clinical_event_pkey PRIMARY KEY ("EventID")
);

CREATE TABLE IF NOT EXISTS public.clinical_event_master
(
    "EventTypeID" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "EventCode" text COLLATE pg_catalog."default" NOT NULL,
    "EventName" text COLLATE pg_catalog."default" NOT NULL,
    "RegistryID" uuid,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT clinical_event_master_pkey PRIMARY KEY ("EventTypeID"),
    CONSTRAINT "clinical_event_master_EventCode_key" UNIQUE ("EventCode")
);

CREATE TABLE IF NOT EXISTS public.complication_master
(
    "ComplicationTypeID" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "ComplicationCode" text COLLATE pg_catalog."default" NOT NULL,
    "ComplicationName" text COLLATE pg_catalog."default" NOT NULL,
    "RegistryID" uuid,
    is_chronic boolean DEFAULT true,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT complication_master_pkey PRIMARY KEY ("ComplicationTypeID"),
    CONSTRAINT "complication_master_ComplicationCode_key" UNIQUE ("ComplicationCode")
);

CREATE TABLE IF NOT EXISTS public.complication_tracking
(
    "ComplicationID" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "PatientID" uuid NOT NULL,
    "ComplicationTypeID" uuid NOT NULL,
    "ConditionID" uuid,
    "DetectedDate" date NOT NULL DEFAULT CURRENT_DATE,
    "Stage" text COLLATE pg_catalog."default",
    "SeverityID" text COLLATE pg_catalog."default",
    "StatusID" text COLLATE pg_catalog."default" DEFAULT 'Active'::text,
    "SourceID" text COLLATE pg_catalog."default",
    "Notes" text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT complication_tracking_pkey PRIMARY KEY ("ComplicationID")
);

CREATE TABLE IF NOT EXISTS public.encounter
(
    "EncounterID" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "Appointment_ID" uuid,
    "PatientID" uuid NOT NULL,
    "ClinicID" uuid NOT NULL,
    "Provider_ID" uuid,
    "EncounterDate" timestamp with time zone NOT NULL DEFAULT now(),
    "SystolicBP" integer,
    "DiastolicBP" integer,
    "Weight" numeric(5, 2),
    "Height" numeric(5, 2),
    "BMI" numeric(4, 2),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT encounter_pkey PRIMARY KEY ("EncounterID")
);

CREATE TABLE IF NOT EXISTS public.gender_master
(
    gender_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    gender_name text COLLATE pg_catalog."default" NOT NULL,
    gender_code character varying(1) COLLATE pg_catalog."default",
    CONSTRAINT gender_master_pkey PRIMARY KEY (gender_id),
    CONSTRAINT gender_master_gender_code_key UNIQUE (gender_code),
    CONSTRAINT gender_master_gender_name_key UNIQUE (gender_name)
);

CREATE TABLE IF NOT EXISTS public.hospital_master
(
    hospital_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    hospital_name text COLLATE pg_catalog."default" NOT NULL,
    hospital_code text COLLATE pg_catalog."default",
    hospital_address text COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT hospital_master_pkey PRIMARY KEY (hospital_id),
    CONSTRAINT hospital_master_hospital_code_key UNIQUE (hospital_code)
);

CREATE TABLE IF NOT EXISTS public.hospital_type_master
(
    "HospitalTypeID" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "TypeName" text COLLATE pg_catalog."default" NOT NULL,
    "TypeDescription" text COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT hospital_type_master_pkey PRIMARY KEY ("HospitalTypeID"),
    CONSTRAINT "hospital_type_master_TypeName_key" UNIQUE ("TypeName")
);

CREATE TABLE IF NOT EXISTS public.lab_observation
(
    "LAB_ObservationID" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "PatientID" uuid NOT NULL,
    "EncounterID" uuid,
    "LabOrderID" uuid,
    "ObservationTypeID" uuid,
    "LOINCCode" text COLLATE pg_catalog."default",
    "Value" numeric(10, 2),
    "Unit" text COLLATE pg_catalog."default",
    "Observation_Date" timestamp with time zone DEFAULT now(),
    is_active boolean DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    site_name text COLLATE pg_catalog."default",
    CONSTRAINT lab_observation_pkey PRIMARY KEY ("LAB_ObservationID")
);

CREATE TABLE IF NOT EXISTS public.lab_order
(
    "LabOrderID" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "PatientID" uuid NOT NULL,
    "OrderedBy" uuid,
    "StatusID" uuid,
    "OrderDate" timestamp with time zone NOT NULL DEFAULT now(),
    is_active boolean DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT lab_order_pkey PRIMARY KEY ("LabOrderID")
);

CREATE TABLE IF NOT EXISTS public.medication
(
    "MedicationID" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "PatientID" uuid NOT NULL,
    "PrescribedBY" uuid,
    "DrugCode" text COLLATE pg_catalog."default",
    "DrugName" text COLLATE pg_catalog."default",
    "Dose" text COLLATE pg_catalog."default",
    "StartDate" date NOT NULL DEFAULT CURRENT_DATE,
    "EndDate" date,
    "AdherenceScore" numeric(5, 2),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    is_active boolean DEFAULT true,
    CONSTRAINT medication_pkey PRIMARY KEY ("MedicationID")
);

CREATE TABLE IF NOT EXISTS public.observation_master
(
    observation_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    patient_id uuid NOT NULL,
    provider_id uuid,
    status_id uuid,
    observation_name text COLLATE pg_catalog."default" NOT NULL,
    observation_value numeric(10, 2) NOT NULL,
    observation_unit text COLLATE pg_catalog."default",
    observation_date date DEFAULT CURRENT_DATE,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT observation_master_pkey PRIMARY KEY (observation_id)
);

CREATE TABLE IF NOT EXISTS public.observation_type_master
(
    "ObservationTypeID" uuid NOT NULL DEFAULT gen_random_uuid(),
    type_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT observation_type_master_pkey PRIMARY KEY ("ObservationTypeID")
);

CREATE TABLE IF NOT EXISTS public.patient_condition
(
    condition_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    patient_id uuid NOT NULL,
    status_id uuid,
    icd10_code text COLLATE pg_catalog."default",
    snomed_code text COLLATE pg_catalog."default",
    onset_date date,
    primary_flag boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT patient_condition_pkey PRIMARY KEY (condition_id)
);

CREATE TABLE IF NOT EXISTS public.patient_master
(
    patient_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    hospital_id uuid NOT NULL,
    abha_id text COLLATE pg_catalog."default",
    patient_name text COLLATE pg_catalog."default" NOT NULL,
    gender_id uuid,
    birth_date date,
    age integer,
    mobile_number text COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    reason_not_active text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    status_id uuid,
    uhid_display character varying(20) COLLATE pg_catalog."default" DEFAULT ('UHID'::text || lpad((nextval('patient_uhid_seq'::regclass))::text, 6, '0'::text)),
    CONSTRAINT patient_master_pkey PRIMARY KEY (patient_id),
    CONSTRAINT patient_master_abha_id_key UNIQUE (abha_id)
);

CREATE TABLE IF NOT EXISTS public.provider_master
(
    provider_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    clinic_id uuid NOT NULL,
    specialty_id uuid,
    first_name text COLLATE pg_catalog."default" NOT NULL,
    last_name text COLLATE pg_catalog."default" NOT NULL,
    registration_number text COLLATE pg_catalog."default",
    designation text COLLATE pg_catalog."default",
    qualification text COLLATE pg_catalog."default",
    contact_number text COLLATE pg_catalog."default",
    email_address text COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    provider_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT provider_master_pkey PRIMARY KEY (provider_id),
    CONSTRAINT provider_master_email_address_key UNIQUE (email_address),
    CONSTRAINT provider_master_registration_number_key UNIQUE (registration_number)
);

CREATE TABLE IF NOT EXISTS public.referral
(
    "ReferralID" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "PatientID" uuid NOT NULL,
    "FromClinic" uuid NOT NULL,
    "ToClinic" uuid NOT NULL,
    "Referral_Reason" text COLLATE pg_catalog."default",
    "Status" text COLLATE pg_catalog."default" DEFAULT 'Pending'::text,
    "ReferralDate" date NOT NULL DEFAULT CURRENT_DATE,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT referral_pkey PRIMARY KEY ("ReferralID")
);

CREATE TABLE IF NOT EXISTS public.registry_enrollment
(
    "EnrollmentID" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "PatientID" uuid NOT NULL,
    "RegistryID" uuid NOT NULL,
    "EnrollmentStatus" text COLLATE pg_catalog."default" DEFAULT 'Active'::text,
    "EnrollmentDate" date NOT NULL DEFAULT CURRENT_DATE,
    "ExitDate" date,
    "ExitReason" text COLLATE pg_catalog."default",
    "Is_Active" boolean DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT registry_enrollment_pkey PRIMARY KEY ("EnrollmentID")
);

CREATE TABLE IF NOT EXISTS public.registry_master
(
    "RegistryID" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "RegistryCode" text COLLATE pg_catalog."default" NOT NULL,
    "RegistryName" text COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default",
    "DiseaseCategory" text COLLATE pg_catalog."default" NOT NULL,
    "CareLevel" text COLLATE pg_catalog."default",
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT registry_master_pkey PRIMARY KEY ("RegistryID"),
    CONSTRAINT "registry_master_RegistryCode_key" UNIQUE ("RegistryCode")
);

CREATE TABLE IF NOT EXISTS public.risk_model_master
(
    "ModelID" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "RegistryID" uuid NOT NULL,
    "ModelName" text COLLATE pg_catalog."default" NOT NULL,
    "Version" text COLLATE pg_catalog."default",
    "AUC" numeric(4, 3),
    "DeploymentDate" date DEFAULT CURRENT_DATE,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT risk_model_master_pkey PRIMARY KEY ("ModelID")
);

CREATE TABLE IF NOT EXISTS public.risk_stratification
(
    "Risk_ID" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "Patient_ID" uuid,
    "RiskScore" numeric(10, 2),
    "RiskCategory" text COLLATE pg_catalog."default",
    "CalculatedDate" date DEFAULT CURRENT_DATE,
    "AlgorithmVersion" text COLLATE pg_catalog."default",
    "RiskFactorsUsed" jsonb,
    "NextReviewDate" date,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT risk_stratification_pkey PRIMARY KEY ("Risk_ID")
);

CREATE TABLE IF NOT EXISTS public.role_list
(
    "User_ID" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "RoleID" uuid NOT NULL,
    "User_Name" text COLLATE pg_catalog."default" NOT NULL,
    "Is_active" boolean DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT role_list_pkey PRIMARY KEY ("User_ID")
);

CREATE TABLE IF NOT EXISTS public.role_master
(
    "RoleID" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "Role_Name" text COLLATE pg_catalog."default" NOT NULL,
    "Is_active" boolean DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    permissions jsonb,
    CONSTRAINT role_master_pkey PRIMARY KEY ("RoleID"),
    CONSTRAINT "role_master_Role_Name_key" UNIQUE ("Role_Name")
);

CREATE TABLE IF NOT EXISTS public.screening_master
(
    "ScreeningTypeID" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "ScreeningCode" text COLLATE pg_catalog."default",
    "ApplicableRegistryID" uuid,
    "RegistryID" uuid,
    "ScreeningName" text COLLATE pg_catalog."default" NOT NULL,
    "FrequencyMonths" integer,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT screening_master_pkey PRIMARY KEY ("ScreeningTypeID")
);

CREATE TABLE IF NOT EXISTS public.screening_tracking
(
    "ScreeningID" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "PatientID" uuid NOT NULL,
    "ScreeningTypeID" uuid NOT NULL,
    "EncounterID" uuid,
    "DueDate" date,
    "CompletedDate" date,
    "NextDueDate" date,
    "ResultID" text COLLATE pg_catalog."default",
    "SeverityID" text COLLATE pg_catalog."default",
    "StatusID" text COLLATE pg_catalog."default" DEFAULT 'Pending'::text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT screening_tracking_pkey PRIMARY KEY ("ScreeningID")
);

CREATE TABLE IF NOT EXISTS public.site_master
(
    site_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    hospital_id uuid NOT NULL,
    site_name text COLLATE pg_catalog."default" NOT NULL,
    site_address text COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    phone_number text COLLATE pg_catalog."default",
    contact_person_name text COLLATE pg_catalog."default",
    contact_person_email text COLLATE pg_catalog."default",
    CONSTRAINT site_master_pkey PRIMARY KEY (site_id)
);

CREATE TABLE IF NOT EXISTS public.specialty_master
(
    specialty_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    specialty_name text COLLATE pg_catalog."default" NOT NULL,
    specialty_code text COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT specialty_master_pkey PRIMARY KEY (specialty_id),
    CONSTRAINT specialty_master_specialty_code_key UNIQUE (specialty_code),
    CONSTRAINT specialty_master_specialty_name_key UNIQUE (specialty_name)
);

CREATE TABLE IF NOT EXISTS public.status_master
(
    status_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    status_name text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    updated_by uuid,
    CONSTRAINT status_master_pkey PRIMARY KEY (status_id),
    CONSTRAINT status_master_status_name_key UNIQUE (status_name)
);

CREATE TABLE IF NOT EXISTS public.user_clinic_mapping
(
    mapping_id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id integer NOT NULL,
    clinic_id uuid NOT NULL,
    assigned_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    is_active boolean DEFAULT true,
    CONSTRAINT user_clinic_mapping_pkey PRIMARY KEY (mapping_id),
    CONSTRAINT user_clinic_mapping_user_id_clinic_id_key UNIQUE (user_id, clinic_id)
);

CREATE TABLE IF NOT EXISTS public.user_site_mapping
(
    mapping_id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id integer NOT NULL,
    site_id uuid NOT NULL,
    assigned_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    is_active boolean DEFAULT true,
    CONSTRAINT user_site_mapping_pkey PRIMARY KEY (mapping_id),
    CONSTRAINT user_site_mapping_user_id_site_id_key UNIQUE (user_id, site_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    suffix character varying(10) COLLATE pg_catalog."default",
    first_name character varying(100) COLLATE pg_catalog."default",
    last_name character varying(100) COLLATE pg_catalog."default",
    gender character varying(20) COLLATE pg_catalog."default",
    role_id uuid,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.alert
    ADD CONSTRAINT "alert_AlertTypeID_fkey" FOREIGN KEY ("AlertTypeID")
    REFERENCES public.activity_type_master (activity_type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.alert
    ADD CONSTRAINT "alert_PatientID_fkey" FOREIGN KEY ("PatientID")
    REFERENCES public.patient_master (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_alert_patient
    ON public.alert("PatientID");


ALTER TABLE IF EXISTS public.appointment
    ADD CONSTRAINT "appointment_ClinicID_fkey" FOREIGN KEY ("ClinicID")
    REFERENCES public.clinic_master (clinic_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.appointment
    ADD CONSTRAINT "appointment_PatientID_fkey" FOREIGN KEY ("PatientID")
    REFERENCES public.patient_master (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_appointment_patient
    ON public.appointment("PatientID");


ALTER TABLE IF EXISTS public.appointment
    ADD CONSTRAINT "appointment_ProviderID_fkey" FOREIGN KEY ("ProviderID")
    REFERENCES public.provider_master (provider_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.careplan
    ADD CONSTRAINT "careplan_ConditionID_fkey" FOREIGN KEY ("ConditionID")
    REFERENCES public.patient_condition (condition_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_careplan_condition
    ON public.careplan("ConditionID");


ALTER TABLE IF EXISTS public.careplan
    ADD CONSTRAINT "careplan_PatientID_fkey" FOREIGN KEY ("PatientID")
    REFERENCES public.patient_master (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_careplan_patient
    ON public.careplan("PatientID");


ALTER TABLE IF EXISTS public.careplan
    ADD CONSTRAINT "careplan_PlanStatus_ID_fkey" FOREIGN KEY ("PlanStatus_ID")
    REFERENCES public.status_master (status_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.careplan_activity
    ADD CONSTRAINT "careplan_activity_ActivityType_ID_fkey" FOREIGN KEY ("ActivityType_ID")
    REFERENCES public.activity_type_master (activity_type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_activity_type_link
    ON public.careplan_activity("ActivityType_ID");


ALTER TABLE IF EXISTS public.careplan_activity
    ADD CONSTRAINT "careplan_activity_CarePlanID_fkey" FOREIGN KEY ("CarePlanID")
    REFERENCES public.careplan ("CarePlanID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_activity_careplan_link
    ON public.careplan_activity("CarePlanID");


ALTER TABLE IF EXISTS public.careplan_activity
    ADD CONSTRAINT "careplan_activity_Status_ID_fkey" FOREIGN KEY ("Status_ID")
    REFERENCES public.status_master (status_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.clinic_master
    ADD CONSTRAINT clinic_master_site_id_fkey FOREIGN KEY (site_id)
    REFERENCES public.site_master (site_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.clinic_master
    ADD CONSTRAINT clinic_master_specialty_id_fkey FOREIGN KEY (specialty_id)
    REFERENCES public.specialty_master (specialty_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.clinical_event
    ADD CONSTRAINT "clinical_event_EventTypeID_fkey" FOREIGN KEY ("EventTypeID")
    REFERENCES public.clinical_event_master ("EventTypeID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_clinical_event_type
    ON public.clinical_event("EventTypeID");


ALTER TABLE IF EXISTS public.clinical_event
    ADD CONSTRAINT "clinical_event_HospitalID_fkey" FOREIGN KEY ("HospitalID")
    REFERENCES public.hospital_master (hospital_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.clinical_event
    ADD CONSTRAINT "clinical_event_PatientID_fkey" FOREIGN KEY ("PatientID")
    REFERENCES public.patient_master (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_clinical_event_patient
    ON public.clinical_event("PatientID");


ALTER TABLE IF EXISTS public.clinical_event_master
    ADD CONSTRAINT "clinical_event_master_RegistryID_fkey" FOREIGN KEY ("RegistryID")
    REFERENCES public.registry_master ("RegistryID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_clinical_event_registry
    ON public.clinical_event_master("RegistryID");


ALTER TABLE IF EXISTS public.complication_master
    ADD CONSTRAINT "complication_master_RegistryID_fkey" FOREIGN KEY ("RegistryID")
    REFERENCES public.registry_master ("RegistryID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_complication_registry
    ON public.complication_master("RegistryID");


ALTER TABLE IF EXISTS public.complication_tracking
    ADD CONSTRAINT "complication_tracking_ComplicationTypeID_fkey" FOREIGN KEY ("ComplicationTypeID")
    REFERENCES public.complication_master ("ComplicationTypeID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_complication_tracking_type
    ON public.complication_tracking("ComplicationTypeID");


ALTER TABLE IF EXISTS public.complication_tracking
    ADD CONSTRAINT "complication_tracking_PatientID_fkey" FOREIGN KEY ("PatientID")
    REFERENCES public.patient_master (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_complication_tracking_patient
    ON public.complication_tracking("PatientID");


ALTER TABLE IF EXISTS public.encounter
    ADD CONSTRAINT "encounter_Appointment_ID_fkey" FOREIGN KEY ("Appointment_ID")
    REFERENCES public.appointment ("AppointmentID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.encounter
    ADD CONSTRAINT "encounter_ClinicID_fkey" FOREIGN KEY ("ClinicID")
    REFERENCES public.clinic_master (clinic_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.encounter
    ADD CONSTRAINT "encounter_PatientID_fkey" FOREIGN KEY ("PatientID")
    REFERENCES public.patient_master (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_encounter_patient
    ON public.encounter("PatientID");


ALTER TABLE IF EXISTS public.encounter
    ADD CONSTRAINT "encounter_Provider_ID_fkey" FOREIGN KEY ("Provider_ID")
    REFERENCES public.provider_master (provider_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.lab_observation
    ADD CONSTRAINT "lab_observation_EncounterID_fkey" FOREIGN KEY ("EncounterID")
    REFERENCES public.encounter ("EncounterID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.lab_observation
    ADD CONSTRAINT "lab_observation_LabOrderID_fkey" FOREIGN KEY ("LabOrderID")
    REFERENCES public.lab_order ("LabOrderID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_obs_order
    ON public.lab_observation("LabOrderID");


ALTER TABLE IF EXISTS public.lab_observation
    ADD CONSTRAINT "lab_observation_ObservationTypeID_fkey" FOREIGN KEY ("ObservationTypeID")
    REFERENCES public.activity_type_master (activity_type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_obs_type
    ON public.lab_observation("ObservationTypeID");


ALTER TABLE IF EXISTS public.lab_observation
    ADD CONSTRAINT "lab_observation_PatientID_fkey" FOREIGN KEY ("PatientID")
    REFERENCES public.patient_master (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_obs_patient
    ON public.lab_observation("PatientID");


ALTER TABLE IF EXISTS public.lab_order
    ADD CONSTRAINT "lab_order_OrderedBy_fkey" FOREIGN KEY ("OrderedBy")
    REFERENCES public.provider_master (provider_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.lab_order
    ADD CONSTRAINT "lab_order_PatientID_fkey" FOREIGN KEY ("PatientID")
    REFERENCES public.patient_master (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_lab_order_patient
    ON public.lab_order("PatientID");


ALTER TABLE IF EXISTS public.lab_order
    ADD CONSTRAINT "lab_order_StatusID_fkey" FOREIGN KEY ("StatusID")
    REFERENCES public.status_master (status_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_lab_order_status
    ON public.lab_order("StatusID");


ALTER TABLE IF EXISTS public.medication
    ADD CONSTRAINT "medication_PatientID_fkey" FOREIGN KEY ("PatientID")
    REFERENCES public.patient_master (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_med_patient
    ON public.medication("PatientID");


ALTER TABLE IF EXISTS public.medication
    ADD CONSTRAINT "medication_PrescribedBY_fkey" FOREIGN KEY ("PrescribedBY")
    REFERENCES public.provider_master (provider_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_med_prescriber
    ON public.medication("PrescribedBY");


ALTER TABLE IF EXISTS public.observation_master
    ADD CONSTRAINT observation_master_patient_id_fkey FOREIGN KEY (patient_id)
    REFERENCES public.patient_master (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.observation_master
    ADD CONSTRAINT observation_master_provider_id_fkey FOREIGN KEY (provider_id)
    REFERENCES public.provider_master (provider_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.observation_master
    ADD CONSTRAINT observation_master_status_id_fkey FOREIGN KEY (status_id)
    REFERENCES public.status_master (status_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.patient_condition
    ADD CONSTRAINT patient_condition_patient_id_fkey FOREIGN KEY (patient_id)
    REFERENCES public.patient_master (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_condition_patient_id
    ON public.patient_condition(patient_id);


ALTER TABLE IF EXISTS public.patient_condition
    ADD CONSTRAINT patient_condition_status_id_fkey FOREIGN KEY (status_id)
    REFERENCES public.status_master (status_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_condition_status_id
    ON public.patient_condition(status_id);


ALTER TABLE IF EXISTS public.patient_master
    ADD CONSTRAINT patient_master_gender_id_fkey FOREIGN KEY (gender_id)
    REFERENCES public.gender_master (gender_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_patient_gender_id
    ON public.patient_master(gender_id);


ALTER TABLE IF EXISTS public.patient_master
    ADD CONSTRAINT patient_master_hospital_id_fkey FOREIGN KEY (hospital_id)
    REFERENCES public.hospital_master (hospital_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_patient_hospital_id
    ON public.patient_master(hospital_id);


ALTER TABLE IF EXISTS public.patient_master
    ADD CONSTRAINT patient_master_status_id_fkey FOREIGN KEY (status_id)
    REFERENCES public.status_master (status_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_patient_status_id
    ON public.patient_master(status_id);


ALTER TABLE IF EXISTS public.provider_master
    ADD CONSTRAINT provider_master_clinic_id_fkey FOREIGN KEY (clinic_id)
    REFERENCES public.clinic_master (clinic_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.provider_master
    ADD CONSTRAINT provider_master_specialty_id_fkey FOREIGN KEY (specialty_id)
    REFERENCES public.specialty_master (specialty_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.referral
    ADD CONSTRAINT "referral_FromClinic_fkey" FOREIGN KEY ("FromClinic")
    REFERENCES public.clinic_master (clinic_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.referral
    ADD CONSTRAINT "referral_PatientID_fkey" FOREIGN KEY ("PatientID")
    REFERENCES public.patient_master (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_referral_patient
    ON public.referral("PatientID");


ALTER TABLE IF EXISTS public.referral
    ADD CONSTRAINT "referral_ToClinic_fkey" FOREIGN KEY ("ToClinic")
    REFERENCES public.clinic_master (clinic_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.registry_enrollment
    ADD CONSTRAINT "registry_enrollment_PatientID_fkey" FOREIGN KEY ("PatientID")
    REFERENCES public.patient_master (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_enrollment_patient
    ON public.registry_enrollment("PatientID");


ALTER TABLE IF EXISTS public.registry_enrollment
    ADD CONSTRAINT "registry_enrollment_RegistryID_fkey" FOREIGN KEY ("RegistryID")
    REFERENCES public.registry_master ("RegistryID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_enrollment_registry
    ON public.registry_enrollment("RegistryID");


ALTER TABLE IF EXISTS public.registry_master
    ADD CONSTRAINT "registry_master_CareLevel_fkey" FOREIGN KEY ("CareLevel")
    REFERENCES public.carelevel_master ("LevelName") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.risk_model_master
    ADD CONSTRAINT "risk_model_master_RegistryID_fkey" FOREIGN KEY ("RegistryID")
    REFERENCES public.registry_master ("RegistryID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_risk_model_registry
    ON public.risk_model_master("RegistryID");


ALTER TABLE IF EXISTS public.risk_stratification
    ADD CONSTRAINT "risk_stratification_Patient_ID_fkey" FOREIGN KEY ("Patient_ID")
    REFERENCES public.patient_master (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_risk_patient
    ON public.risk_stratification("Patient_ID");


ALTER TABLE IF EXISTS public.role_list
    ADD CONSTRAINT "role_list_RoleID_fkey" FOREIGN KEY ("RoleID")
    REFERENCES public.role_master ("RoleID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_role_list_role
    ON public.role_list("RoleID");


ALTER TABLE IF EXISTS public.screening_master
    ADD CONSTRAINT "screening_master_RegistryID_fkey" FOREIGN KEY ("RegistryID")
    REFERENCES public.registry_master ("RegistryID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.screening_tracking
    ADD CONSTRAINT "screening_tracking_EncounterID_fkey" FOREIGN KEY ("EncounterID")
    REFERENCES public.encounter ("EncounterID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.screening_tracking
    ADD CONSTRAINT "screening_tracking_PatientID_fkey" FOREIGN KEY ("PatientID")
    REFERENCES public.patient_master (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_screening_tracking_patient
    ON public.screening_tracking("PatientID");


ALTER TABLE IF EXISTS public.screening_tracking
    ADD CONSTRAINT "screening_tracking_ScreeningTypeID_fkey" FOREIGN KEY ("ScreeningTypeID")
    REFERENCES public.screening_master ("ScreeningTypeID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.site_master
    ADD CONSTRAINT site_master_hospital_id_fkey FOREIGN KEY (hospital_id)
    REFERENCES public.hospital_master (hospital_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_clinic_mapping
    ADD CONSTRAINT user_clinic_mapping_clinic_id_fkey FOREIGN KEY (clinic_id)
    REFERENCES public.clinic_master (clinic_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_clinic_mapping
    ADD CONSTRAINT user_clinic_mapping_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_site_mapping
    ADD CONSTRAINT user_site_mapping_site_id_fkey FOREIGN KEY (site_id)
    REFERENCES public.site_master (site_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_site_mapping
    ADD CONSTRAINT user_site_mapping_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT fk_user_role FOREIGN KEY (role_id)
    REFERENCES public.role_master ("RoleID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;

END;